// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
 
using System.Reflection;
 
[assembly: AssemblyVersion("0.6.573.2747")]
[assembly: AssemblyFileVersion("0.6.573.2747")]
